# Generated by Django 2.2.7 on 2019-11-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='id_encargado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Responsable'),
        ),
    ]
