# Generated by Django 2.2.7 on 2019-11-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191126_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='id',
        ),
        migrations.AddField(
            model_name='resources',
            name='serial',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
