# Generated by Django 2.2.7 on 2019-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191127_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='tipo',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Oficina', 'Oficina'), ('Cafeteria', 'Cafeteria')], max_length=12),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='tipo',
            field=models.CharField(choices=[('Area', 'Area'), ('Persona', 'Persona')], max_length=8),
        ),
    ]
