# Generated by Django 2.2.7 on 2019-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191127_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='encargado',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
