# Generated by Django 2.2.7 on 2019-11-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resources_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='encargado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Resources.encargado+', to='api.Responsable', verbose_name='Responsables'),
        ),
    ]
