# Generated by Django 2.2.7 on 2019-11-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191127_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='encargado',
        ),
        migrations.AddField(
            model_name='resources',
            name='nombre_encargado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Resources.nombre_encargado+', to='api.Responsable', verbose_name='Responsables'),
        ),
    ]
