# Generated by Django 2.2.7 on 2019-11-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191127_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='nombre_encargado',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Resources.nombre_encargado+', to='api.Responsable', verbose_name='Responsables'),
        ),
    ]
