# Generated by Django 2.2.7 on 2019-11-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191127_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='nombre_encargado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Resources.nombre_encargado+', to='api.Responsable'),
        ),
    ]
