# Generated by Django 2.2.7 on 2019-11-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191127_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={},
        ),
    ]
