# Generated by Django 2.2.7 on 2019-11-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191127_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='nombre_encargado',
        ),
    ]
