# Generated by Django 2.2.7 on 2019-11-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_resources_nombre_encargado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsable',
            options={'verbose_name_plural': 'Responsables'},
        ),
    ]
