# Generated by Django 2.2.7 on 2019-11-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191127_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
