# Generated by Django 2.2.7 on 2019-11-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_resources_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='test',
        ),
    ]
